ARG RUBY_VERSION=4.0.1
FROM docker.io/library/ruby:$RUBY_VERSION

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential curl git libpq-dev libyaml-dev pkg-config unzip && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

ENV BUN_INSTALL=/usr/local/bun
ENV PATH=/usr/local/bun/bin:$PATH
ARG BUN_VERSION=1.3.8
RUN curl -fsSL https://bun.sh/install | bash -s -- "bun-v${BUN_VERSION}"

COPY vendor/* ./vendor/
COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY package.json bun.lock* ./
RUN bun install --frozen-lockfile

COPY . .

RUN groupadd --system --gid 1000 rails && useradd rails --uid 1000 --gid 1000 --create-home --shell /bin/bash && chown -R rails:rails /rails /usr/local
USER rails:rails

ENTRYPOINT ["/rails/bin/docker-entrypoint"]

EXPOSE 80
CMD ["./bin/thrust", "./bin/rails", "server"]
